# Generated by Django 4.2.5 on 2023-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'verbose_name_plural': 'Ordenes de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='repuesto',
            name='garantia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('func', 'Funcionamiento'), ('mant', 'Mantenimiento'), ('des', 'Desechado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='frecuencia',
            field=models.CharField(choices=[('DIA', 'Diariamente'), ('SEM', 'Semanal'), ('MEN', 'Mensual'), ('TRI', 'Trimestral'), ('ANU', 'Anual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado_orden',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'En proceso'), ('COM', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio $ Arg.'),
        ),
    ]
