# Generated by Django 4.2.5 on 2023-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_ordentrabajo_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='cant_garantia',
            field=models.IntegerField(default=0, verbose_name='Cantidad meses de garantia'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='garantia',
            field=models.BooleanField(default=False),
        ),
    ]
