# Generated by Django 4.2.5 on 2023-09-14 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_repuesto_cant_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='fecha_gtia',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 14), null=True),
        ),
    ]
